// <auto-generated />
using System;
using BusinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203062332_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.BranchAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BranchAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "admin",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "member@gmail.com",
                            FullName = "Member",
                            Password = "member",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "manager@gmail.com",
                            FullName = "Manager",
                            Password = "manager",
                            Role = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "staff@gmail.com",
                            FullName = "Staff",
                            Password = "staff",
                            Role = 4
                        });
                });

            modelBuilder.Entity("BusinessObject.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            FromCountry = "USA",
                            Name = "Rings"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            FromCountry = "Vietnam",
                            Name = "Necklaces"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            FromCountry = "Japan",
                            Name = "Bracelets"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            FromCountry = "China",
                            Name = "Earrings"
                        });
                });

            modelBuilder.Entity("BusinessObject.SilverJewelry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MetalWeight")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SilverJewelries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateOnly(1999, 1, 1),
                            Description = "Description 1",
                            MetalWeight = 0.1f,
                            Name = "Silver Jewelry 1",
                            Price = 50.0m,
                            ProductionYear = 1999
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateOnly(2000, 2, 1),
                            Description = "Description 2",
                            MetalWeight = 1.1f,
                            Name = "Silver Jewelry 2",
                            Price = 10.0m,
                            ProductionYear = 2000
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedDate = new DateOnly(2021, 12, 12),
                            Description = "Description 3",
                            MetalWeight = 2.1f,
                            Name = "Silver Jewelry 3",
                            Price = 24.5m,
                            ProductionYear = 2021
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedDate = new DateOnly(1997, 1, 1),
                            Description = "Description 4",
                            MetalWeight = 3.1f,
                            Name = "Silver Jewelry 4",
                            Price = 54.0m,
                            ProductionYear = 1997
                        });
                });

            modelBuilder.Entity("BusinessObject.SilverJewelry", b =>
                {
                    b.HasOne("BusinessObject.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
